const LOADING = 'LOADING'
const ERROR = 'ERROR'
const REQUEST_SUCCESS = 'REQUEST_SUCCESS'
const NOT_PERSIST = 'NOT_PERSIST'

const REQUEST_METHOD = {
  POST: 'POST',
  GET: 'GET',
  DELETE: 'DELETE',
  PUT: 'PUT'
}

export {LOADING, ERROR, REQUEST_SUCCESS, NOT_PERSIST, REQUEST_METHOD}
